import type { ToolRichContent } from '../types';
import { privacyFaq, defaultCta } from '../helpers';

export const PDF_EXTRACT_TEXT_CONTENT: Record<'en' | 'pt' | 'es', ToolRichContent> = {
  en: {
    title: 'Extract Text from PDF Online Offline | PDFWINDOWS',
    description:
      'Pull selectable text from native PDFs in your browser. Fast plain-text export for editing, search, and data pipelines — no upload, full privacy.',
    keywords:
      'extract text pdf, pdf to txt, copy pdf text offline, get text from pdf browser, pdf text extractor free',
    h1: 'Extract Text from PDF',
    intro:
      'When a PDF already contains real text — exported from Word, generated by accounting software, or downloaded from a government portal — you should not need OCR or a cloud parser to copy it. Extract Text reads the embedded character streams directly and writes plain output you can paste into spreadsheets, code editors, translation tools, or archival search indexes. Uploading those same files to online extractors sends contract language, employee data, and API documentation through someone else\'s logging pipeline. PDFWINDOWS extracts text locally: the browser parses the PDF structure on your device and delivers a text file without network transfer of document contents.',
    toolName: 'Extract Text from PDF',
    benefits: [
      'Instant extraction from text-based PDFs',
      'No server upload — content stays on your device',
      'Faster and more accurate than OCR on native PDFs',
      'Export plain text for editing and automation',
      'Works offline after page load',
    ],
    useCases: [
      {
        title: 'Legal and policy review',
        body:
          'Counsel and compliance analysts paste clauses into comparison tools and redline trackers. Extracting text from native regulatory PDFs locally keeps draft policy language out of third-party NLP services while still enabling diff workflows.',
      },
      {
        title: 'Data and research pipelines',
        body:
          'Data scientists pull tables and paragraphs from published reports for NLP experiments. Browser extraction provides a quick plain-text snapshot without shipping entire corpora to external parsing APIs with unclear retention policies.',
      },
      {
        title: 'Repurposing documentation',
        body:
          'Technical writers migrate legacy PDF manuals into Markdown wikis. Extract Text accelerates the first pass — headings and body copy land in an editor where structure can be cleaned up manually or with scripts.',
      },
      {
        title: 'Accessibility and screen-reader prep',
        body:
          'Teams audit whether PDFs expose readable text layers. Extraction verifies that assistive technologies will find content; when output is empty, the file is likely image-only and needs PDF OCR instead.',
      },
      {
        title: 'Quote and citation workflows',
        body:
          'Journalists and academics pull exact wording from press releases and filings. Local extraction avoids mis-typing sensitive quotes and prevents embargoed material from appearing in cloud conversion logs.',
      },
    ],
    howItWorks: [
      'Upload a PDF that contains embedded text.',
      'Select Extract Text from the tool menu.',
      'The browser reads text objects and encoding from each page.',
      'Review or download the plain-text output file.',
    ],
    tips: [
      'If extraction returns gibberish or nothing, the PDF may be scan-only — use PDF OCR instead.',
      'Complex multi-column layouts may lose reading order — expect manual cleanup.',
      'Password-protected files must be unlocked before text streams can be read.',
      'Extract before compressing if you need a text archive of pre-optimization content.',
      'Compare a sample page against the PDF visually after extraction.',
      'For mixed PDFs, split scan sections and process text sections separately.',
      'Save extracted text with a dated filename when building compliance archives so reviewers can trace which PDF version produced each export.',
    ],
    sections: [
      {
        id: 'native-text-vs-ocr',
        heading: 'Native text extraction versus OCR',
        level: 2,
        paragraphs: [
          'Native extraction copies characters the PDF author embedded — exact spelling, punctuation, and Unicode symbols when encoding is correct. OCR guesses letters from pixels and introduces recognition errors on poor scans.',
          'Always try Extract Text first on unknown files. If you can highlight individual words in a desktop reader, extraction should work. If selection grabs a whole-page image, switch to PDF OCR.',
        ],
      },
      {
        id: 'layout-limitations',
        heading: 'Tables, columns, and reading order',
        level: 2,
        paragraphs: [
          'PDF stores drawing instructions, not semantic HTML. Extracted text may arrive in an order that does not match visual columns, especially in financial tables and magazine layouts. Treat output as raw material for scripts or manual restructuring.',
        ],
        bullets: [
          'Single-column letters extract cleanly',
          'Multi-column newspapers may interleave lines incorrectly',
          'Tables often need spreadsheet export from the source app instead',
        ],
      },
      {
        id: 'privacy-extraction',
        heading: 'Why local extraction matters for confidential PDFs',
        level: 2,
        paragraphs: [
          'Cloud text extractors process full document binaries server-side. Even when vendors promise deletion, you cannot verify handling of HR records, security audits, or customer contracts. PDFWINDOWS never transmits file bytes for this operation — parsing runs in JavaScript against memory-loaded PDFs.',
          'Treat extracted output as sensitive as the source PDF: store text exports in the same access-controlled folders and retention schedules you apply to the original file.',
        ],
      },
      {
        id: 'extract-workflow',
        heading: 'Using extracted text downstream',
        level: 2,
        paragraphs: [
          'Plain text feeds many tools: full-text search indexes, translation APIs you control, CSV enrichment scripts, and email snippets. Pair extraction with merge when compiling multiple text exports, or with TXT to PDF when you need a clean rereadable document after editing.',
          'Compliance officers often diff extracted policy text year-over-year in git repositories. Keeping extraction local means annual regulatory updates never sit in a vendor corpus used to train unrelated models.',
        ],
        bullets: [
          'PDF OCR — when pages are images, not text',
          'TXT to PDF — rebuild PDF after heavy text edits',
          'CSV to JSON — structure data extracted into spreadsheets first',
        ],
      },
    ],
    faq: [
      ...privacyFaq('en'),
      {
        q: 'Will extraction preserve formatting?',
        a: 'No. Output is plain text without bold, fonts, or hyperlinks. Formatting must be recreated in your destination editor.',
      },
      {
        q: 'Can I extract from scanned PDFs?',
        a: 'Scanned PDFs usually lack text layers. Use PDF OCR to recognize characters first, or export images and run Image OCR.',
      },
      {
        q: 'Does extraction include hidden or metadata text?',
        a: 'Output reflects visible text objects on pages. Hidden layers and document metadata may not appear unless exposed as page content.',
      },
      {
        q: 'How large a PDF can I extract?',
        a: 'Limits depend on browser memory, not our servers. Very large files may take longer; try splitting first if the tab becomes unresponsive.',
      },
      {
        q: 'Is extracted text searchable in the output file?',
        a: 'The downloaded .txt file is plain text — open it in any editor and use local search. It is not a PDF; convert back with TXT to PDF if needed.',
      },
    ],
    relatedTools: ['/pdf-ocr', '/txt-to-pdf', '/pdf-split'],
    cta: defaultCta('en', 'Extract Text from PDF'),
  },
  pt: {
    title: 'Extrair Texto de PDF Online Offline | PDFWINDOWS',
    description:
      'Extraia texto selecionável de PDFs nativos no navegador. Exportação rápida em texto puro para edição e busca — sem upload, privacidade total.',
    keywords:
      'extrair texto pdf, pdf para txt, copiar texto pdf offline, texto de pdf navegador, extrator texto pdf gratis',
    h1: 'Extrair Texto de PDF',
    intro:
      'Quando um PDF já contém texto real — exportado do Word, gerado por sistema contábil ou baixado de portal governamental — você não deveria precisar de OCR ou parser na nuvem para copiá-lo. Extrair Texto lê os fluxos de caracteres embutidos e gera saída em texto puro para colar em planilhas, editores de código, tradutores ou índices de busca. Enviar esses arquivos a extratores online passa linguagem contratual, dados de funcionários e documentação de API por pipelines de log de terceiros. O PDFWINDOWS extrai texto localmente: o navegador interpreta a estrutura do PDF no dispositivo e entrega arquivo de texto sem transferir conteúdo pela rede.',
    toolName: 'Extrair Texto de PDF',
    benefits: [
      'Extração instantânea de PDFs com texto embutido',
      'Sem upload — conteúdo permanece no dispositivo',
      'Mais rápido e preciso que OCR em PDFs nativos',
      'Exporte texto puro para edição e automação',
      'Funciona offline após carregar a página',
    ],
    useCases: [
      {
        title: 'Revisão jurídica e de políticas',
        body:
          'Advogados e analistas de compliance colam cláusulas em ferramentas de comparação. Extrair texto de PDFs regulatórios nativos localmente mantém rascunhos de política fora de serviços NLP de terceiros enquanto permite fluxos de diff.',
      },
      {
        title: 'Pipelines de dados e pesquisa',
        body:
          'Cientistas de dados extraem tabelas e parágrafos de relatórios publicados para experimentos NLP. Extração no navegador fornece snapshot em texto puro sem enviar corpora inteiros a APIs de parsing com retenção incerta.',
      },
      {
        title: 'Reaproveitar documentação',
        body:
          'Redatores técnicos migram manuais PDF legados para wikis Markdown. Extrair Texto acelera a primeira passagem — títulos e corpo caem no editor para limpeza manual ou com scripts.',
      },
      {
        title: 'Acessibilidade e leitores de tela',
        body:
          'Equipes auditam se PDFs expõem camadas de texto legíveis. A extração verifica que tecnologias assistivas encontrarão conteúdo; saída vazia indica arquivo só-imagem que precisa de OCR de PDF.',
      },
      {
        title: 'Citações e aspas',
        body:
          'Jornalistas e acadêmicos puxam redação exata de releases e documentos públicos. Extração local evita erros de digitação em citações sensíveis e impede material sob embargo em logs de conversão na nuvem.',
      },
    ],
    howItWorks: [
      'Envie um PDF que contenha texto embutido.',
      'Selecione Extrair Texto no menu de ferramentas.',
      'O navegador lê objetos de texto e codificação de cada página.',
      'Revise ou baixe o arquivo de saída em texto puro.',
    ],
    tips: [
      'Se a extração retornar lixo ou nada, o PDF pode ser só scan — use OCR de PDF.',
      'Layouts multicolumna complexos podem perder ordem de leitura — espere limpeza manual.',
      'Arquivos com senha precisam ser desbloqueados antes de ler fluxos de texto.',
      'Extraia antes de comprimir se precisar de arquivo de texto do conteúdo original.',
      'Compare uma página amostra com o PDF visualmente após extração.',
      'Em PDFs mistos, divida seções escaneadas e processe seções de texto separadamente.',
      'Salve texto extraído com nome datado ao montar arquivos de conformidade para revisores rastrearem qual versão do PDF gerou cada exportação.',
    ],
    sections: [
      {
        id: 'texto-nativo-vs-ocr',
        heading: 'Extração de texto nativo versus OCR',
        level: 2,
        paragraphs: [
          'Extração nativa copia caracteres que o autor embutiu — ortografia, pontuação e símbolos Unicode quando a codificação está correta. OCR adivinha letras a partir de pixels e introduz erros em scans ruins.',
          'Sempre tente Extrair Texto primeiro em arquivos desconhecidos. Se você destaca palavras individuais no leitor, a extração deve funcionar. Se a seleção pega a página inteira como imagem, use OCR de PDF.',
        ],
      },
      {
        id: 'limitacoes-layout',
        heading: 'Tabelas, colunas e ordem de leitura',
        level: 2,
        paragraphs: [
          'PDF armazena instruções de desenho, não HTML semântico. Texto extraído pode chegar em ordem que não corresponde às colunas visuais, especialmente em tabelas financeiras e layouts de revista. Trate a saída como matéria-prima para scripts ou reestruturação manual.',
        ],
        bullets: [
          'Cartas de coluna única extraem de forma limpa',
          'Jornais multicolumna podem intercalar linhas incorretamente',
          'Tabelas frequentemente precisam de export da aplicação fonte',
        ],
      },
      {
        id: 'privacidade-extracao',
        heading: 'Por que extração local importa para PDFs confidenciais',
        level: 2,
        paragraphs: [
          'Extratores na nuvem processam binários completos no servidor. Mesmo com promessas de exclusão, você não verifica o tratamento de registros de RH, auditorias de segurança ou contratos de clientes. O PDFWINDOWS nunca transmite bytes de arquivo nesta operação — o parsing roda em JavaScript contra PDFs carregados na memória.',
        ],
      },
      {
        id: 'fluxo-extracao',
        heading: 'Usando texto extraído depois',
        level: 2,
        paragraphs: [
          'Texto puro alimenta muitas ferramentas: índices de busca full-text, APIs de tradução que você controla, scripts de enriquecimento CSV e trechos de e-mail. Combine extração com mesclar ao compilar várias exportações, ou com TXT para PDF quando precisar de documento legível após edição pesada.',
          'Oficiais de conformidade costumam comparar texto de políticas extraído ano a ano em repositórios git. Manter extração local evita que atualizações regulatórias anuais fiquem em corpus de fornecedor usado para treinar modelos não relacionados.',
        ],
        bullets: [
          'OCR de PDF — quando páginas são imagens, não texto',
          'TXT para PDF — reconstruir PDF após edições de texto',
          'CSV para JSON — estruturar dados extraídos para planilhas primeiro',
        ],
      },
    ],
    faq: [
      ...privacyFaq('pt'),
      {
        q: 'A extração preserva formatação?',
        a: 'Não. A saída é texto puro sem negrito, fontes ou hyperlinks. Formatação deve ser recriada no editor de destino.',
      },
      {
        q: 'Posso extrair de PDFs escaneados?',
        a: 'PDFs escaneados geralmente não têm camada de texto. Use OCR de PDF para reconhecer caracteres ou exporte imagens e rode OCR de Imagem.',
      },
      {
        q: 'A extração inclui texto oculto ou de metadados?',
        a: 'A saída reflete objetos de texto visíveis nas páginas. Camadas ocultas e metadados do documento podem não aparecer.',
      },
      {
        q: 'Qual tamanho máximo de PDF posso extrair?',
        a: 'Limites dependem da memória do navegador, não de nossos servidores. Arquivos muito grandes podem demorar; divida primeiro se a aba travar.',
      },
      {
        q: 'O texto extraído é pesquisável no arquivo de saída?',
        a: 'O .txt baixado é texto puro — abra em qualquer editor e use busca local. Não é PDF; converta de volta com TXT para PDF se necessário.',
      },
    ],
    relatedTools: ['/pdf-ocr', '/txt-to-pdf', '/pdf-split'],
    cta: defaultCta('pt', 'Extrair Texto de PDF'),
  },
  es: {
    title: 'Extraer Texto de PDF Online Offline | PDFWINDOWS',
    description:
      'Extraiga texto seleccionable de PDF nativos en su navegador. Exportación rápida en texto plano para edición y búsqueda — sin subida, privacidad total.',
    keywords:
      'extraer texto pdf, pdf a txt, copiar texto pdf offline, texto de pdf navegador, extractor texto pdf gratis',
    h1: 'Extraer Texto de PDF',
    intro:
      'Cuando un PDF ya contiene texto real — exportado de Word, generado por software contable o descargado de un portal gubernamental — no debería necesitar OCR ni un analizador en la nube para copiarlo. Extraer Texto lee los flujos de caracteres incrustados y genera salida en texto plano para pegar en hojas de cálculo, editores de código, traductores o índices de búsqueda. Subir esos archivos a extractores en línea envía lenguaje contractual, datos de empleados y documentación API por pipelines de registro de terceros. PDFWINDOWS extrae texto localmente: el navegador interpreta la estructura PDF en su dispositivo y entrega archivo de texto sin transferir contenido por la red.',
    toolName: 'Extraer Texto de PDF',
    benefits: [
      'Extracción instantánea de PDF con texto incrustado',
      'Sin subida — el contenido permanece en su dispositivo',
      'Más rápido y preciso que OCR en PDF nativos',
      'Exporte texto plano para edición y automatización',
      'Funciona sin conexión tras cargar la página',
    ],
    useCases: [
      {
        title: 'Revisión legal y de políticas',
        body:
          'Abogados y analistas de cumplimiento pegan cláusulas en herramientas de comparación. Extraer texto de PDF regulatorios nativos localmente mantiene borradores de política fuera de servicios NLP de terceros mientras permite flujos de diff.',
      },
      {
        title: 'Pipelines de datos e investigación',
        body:
          'Científicos de datos extraen tablas y párrafos de informes publicados para experimentos NLP. La extracción en navegador proporciona instantánea en texto plano sin enviar corpora enteros a APIs de análisis con retención incierta.',
      },
      {
        title: 'Reutilizar documentación',
        body:
          'Redactores técnicos migran manuales PDF heredados a wikis Markdown. Extraer Texto acelera el primer paso — títulos y cuerpo llegan al editor para limpieza manual o con scripts.',
      },
      {
        title: 'Accesibilidad y lectores de pantalla',
        body:
          'Los equipos auditan si los PDF exponen capas de texto legibles. La extracción verifica que las tecnologías asistivas encontrarán contenido; salida vacía indica archivo solo-imagen que necesita OCR de PDF.',
      },
      {
        title: 'Citas y comillas',
        body:
          'Periodistas y académicos extraen redacción exacta de comunicados y documentos públicos. La extracción local evita errores al citar material sensible e impide que contenido bajo embargo aparezca en registros de conversión en la nube.',
      },
    ],
    howItWorks: [
      'Suba un PDF que contenga texto incrustado.',
      'Seleccione Extraer Texto en el menú de herramientas.',
      'El navegador lee objetos de texto y codificación de cada página.',
      'Revise o descargue el archivo de salida en texto plano.',
    ],
    tips: [
      'Si la extracción devuelve basura o nada, el PDF puede ser solo escaneo — use OCR de PDF.',
      'Diseños multicolumna complejos pueden perder orden de lectura — espere limpieza manual.',
      'Los archivos con contraseña deben desbloquearse antes de leer flujos de texto.',
      'Extraiga antes de comprimir si necesita archivo de texto del contenido original.',
      'Compare una página muestra con el PDF visualmente tras la extracción.',
      'En PDF mixtos, divida secciones escaneadas y procese secciones de texto por separado.',
    ],
    sections: [
      {
        id: 'texto-nativo-vs-ocr',
        heading: 'Extracción de texto nativo frente a OCR',
        level: 2,
        paragraphs: [
          'La extracción nativa copia caracteres que el autor incrustó — ortografía, puntuación y símbolos Unicode cuando la codificación es correcta. OCR adivina letras desde píxeles e introduce errores en escaneos pobres.',
          'Siempre intente Extraer Texto primero en archivos desconocidos. Si puede resaltar palabras individuales en el lector, la extracción debería funcionar. Si la selección toma la página entera como imagen, use OCR de PDF.',
        ],
      },
      {
        id: 'limitaciones-diseno',
        heading: 'Tablas, columnas y orden de lectura',
        level: 2,
        paragraphs: [
          'PDF almacena instrucciones de dibujo, no HTML semántico. El texto extraído puede llegar en orden que no coincide con columnas visuales, especialmente en tablas financieras y diseños de revista. Trate la salida como materia prima para scripts o reestructuración manual.',
        ],
        bullets: [
          'Cartas de columna única extraen limpiamente',
          'Periódicos multicolumna pueden intercalar líneas incorrectamente',
          'Las tablas a menudo necesitan exportación desde la aplicación fuente',
        ],
      },
      {
        id: 'privacidad-extraccion',
        heading: 'Por qué la extracción local importa para PDF confidenciales',
        level: 2,
        paragraphs: [
          'Los extractores en la nube procesan binarios completos en el servidor. Incluso con promesas de borrado, no puede verificar el manejo de registros de RR. HH., auditorías de seguridad o contratos de clientes. PDFWINDOWS nunca transmite bytes de archivo en esta operación — el análisis corre en JavaScript contra PDF cargados en memoria.',
        ],
      },
      {
        id: 'flujo-extraccion',
        heading: 'Usar texto extraído después',
        level: 2,
        paragraphs: [
          'El texto plano alimenta muchas herramientas: índices de búsqueda full-text, APIs de traducción que usted controla, scripts de enriquecimiento CSV y fragmentos de correo. Combine extracción con unir al compilar varias exportaciones, o con TXT a PDF cuando necesite documento legible tras edición pesada.',
          'Oficiales de cumplimiento suelen comparar texto de políticas extraído año tras año en repositorios git. Mantener extracción local evita que actualizaciones regulatorias anuales queden en corpus de proveedor usado para entrenar modelos no relacionados.',
        ],
        bullets: [
          'OCR de PDF — cuando las páginas son imágenes, no texto',
          'TXT a PDF — reconstruir PDF tras ediciones de texto',
          'CSV a JSON — estructurar datos extraídos a hojas de cálculo primero',
        ],
      },
    ],
    faq: [
      ...privacyFaq('es'),
      {
        q: '¿La extracción preserva el formato?',
        a: 'No. La salida es texto plano sin negrita, fuentes ni hipervínculos. El formato debe recrearse en su editor de destino.',
      },
      {
        q: '¿Puedo extraer de PDF escaneados?',
        a: 'Los PDF escaneados generalmente carecen de capa de texto. Use OCR de PDF para reconocer caracteres o exporte imágenes y ejecute OCR de Imagen.',
      },
      {
        q: '¿La extracción incluye texto oculto o de metadatos?',
        a: 'La salida refleja objetos de texto visibles en páginas. Capas ocultas y metadatos del documento pueden no aparecer.',
      },
      {
        q: '¿Qué tamaño máximo de PDF puedo extraer?',
        a: 'Los límites dependen de la memoria del navegador, no de nuestros servidores. Archivos muy grandes pueden tardar; divida primero si la pestaña se bloquea.',
      },
      {
        q: '¿El texto extraído es buscable en el archivo de salida?',
        a: 'El .txt descargado es texto plano — ábralo en cualquier editor y use búsqueda local. No es PDF; convierta de nuevo con TXT a PDF si lo necesita.',
      },
    ],
    relatedTools: ['/pdf-ocr', '/txt-to-pdf', '/pdf-split'],
    cta: defaultCta('es', 'Extraer Texto de PDF'),
  },
};
